name: WildPrisonCore
version: ${project.version}
main: me.drawethree.wildprisoncore.WildPrisonCore
depend: [helper, Vault, PlaceholderAPI, WorldGuard, WorldEdit, JetsPrisonMines]
authors: [Drawethree]
