sql:
  host: localhost
  port: 3306
  database: dbName
  username: dbUser
  password: dbPass
messages:
  not_enough_tokens: "&cYou do not have enough tokens!"
  your_tokens: "&eYour Tokens: %tokens%"
  other_tokens: "&e%player%'s Tokens: %tokens%"
  withdraw_successful: "&aYou have withdrawn &e%value%x %amount% Tokens!"
  admin_set_tokens: "&aSuccessfuly set &e%player%'s &atokens to &e%tokens%."
  admin_give_tokens: "&aSuccessfuly given &e%tokens% &atokens to &e%player%."
  admin_remove_tokens: "&aSuccessfuly removed &e%tokens% &atokens from &e%player%."
  not_token_item: "&cThis is not a token item!"
  tokens_redeem: "&eYou redeemed %tokens% tokens."
  tokens_send: "&eYou have sent %tokens% to %player%"
  tokens_received: "&eYou received %tokens% from %player%."
  not_a_number: "&c%input% is not a number!"
  player_not_online: "&cPlayer &e%player% &cis not online!"

