auto-miner-region:
  name: automine
  world: world
  money: 1000
  tokens: 10
messages:
  auto_miner_enabled: "&aYou are now in &a&lAUTO-MINER &amode."
  auto_miner_disabled: "&cYou don't have &c&lAUTO-MINER &ctime."
  auto_miner_time: "&e&lAUTOMINER &8» &7You have &f%time% &7seconds of Auto-Miner time."
  auto_miner_time_add: "&e&lAUTOMINER &8» &7You added &f%time% seconds &7to &f%player%&7."

