# Should plugin show debug messages?
debug-mode: false
# Database type (SQLite, MySQL)
database_type: SQLite
# MySQL connection details
mysql:
  host: localhost
  port: 3306
  database: dbName
  username: dbUser
  password: dbPass
# Enabling / Disabling of specific modules
modules:
  tokens: true
  gems: true
  ranks: true
  prestiges: true
  multipliers: true
  enchants: true
  autosell: true
  autominer: true
  pickaxe_levels: true
  gangs: true
  mines: true
  history: true
# List of supported pickaxes by UPC Enchants
supported-pickaxes:
  - DIAMOND_PICKAXE
# Aliases for main command
main-command-aliases:
  - upc
  - prisoncore
  - ultraprison
  - prison
  - ultraprisoncore