name: UltraPrisonCore
version: ${project.version}
main: dev.drawethree.ultraprisoncore.UltraPrisonCore
depend: [ Vault, WorldGuard, WorldEdit, helper ]
softdepend:
  - PlaceholderAPI
  - JetsPrisonMines
  - MVdWPlaceholderAPI
  - Multiverse-Core
  - UltraBackpacks
authors: [ Drawethree ]
api-version: 1.13
load: POSTWORLD
website: www.drawethree.dev
