name: WildPrisonEnchants
version: ${project.version}
main: me.drawethree.wildprisonenchants.WildPrisonEnchants
depend: [helper, WildPrisonTokens, Vault, WorldGuard]
softdepend: [PlaceholderAPI]
authors: [Drawethree]
