name: WildPrisonAutoSell
version: ${project.version}
main: me.drawethree.me.drawethree.wildprisoncore.autosell.WildPrisonAutoSell
api-version: 1.13
depend: [helper, Vault, WorldGuard]
authors: [Drawethree]
